// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package resources

import "fyne.io/fyne/v2"

var padLockOpenImageResource = &fyne.StaticResource{
	StaticName: "lock-open.svg",
	StaticContent: []byte(
		"<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools -->\n<svg width=\"800px\" height=\"800px\" viewBox=\"0 0 16 16\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\">\n  <rect width=\"16\" height=\"16\" id=\"icon-bound\" fill=\"none\" />\n  <path d=\"M12.25,7H12V4c0-1.653-1.347-3-3-3H7C5.347,1,4,2.347,4,4v1h2V4c0-0.55,0.45-1,1-1h2c0.55,0,1,0.45,1,1v3H3.75 C3.338,7,3,7.338,3,7.75v6.5C3,14.662,3.338,15,3.75,15h8.5c0.412,0,0.75-0.338,0.75-0.75v-6.5C13,7.338,12.662,7,12.25,7z\" />\n</svg>"),
}
var padLockClosedImageResource = &fyne.StaticResource{
	StaticName: "lock-closed.svg",
	StaticContent: []byte(
		"<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools -->\n<svg width=\"800px\" height=\"800px\" viewBox=\"0 0 16 16\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\">\n  <rect width=\"16\" height=\"16\" id=\"icon-bound\" fill=\"none\" />\n  <path d=\"M12.25,7H12V4c0-1.653-1.347-3-3-3H7C5.347,1,4,2.347,4,4v3H3.75C3.338,7,3,7.338,3,7.75v6.5C3,14.663,3.338,15,3.75,15h8.5 c0.413,0,0.75-0.337,0.75-0.75v-6.5C13,7.338,12.663,7,12.25,7z M6,4c0-0.55,0.45-1,1-1h2c0.55,0,1,0.45,1,1v3H6V4z\" />\n</svg>"),
}
